export const USER_ACTIONS = {
    GET_USER_SETTINGS: "GET_USER_SETTINGS",
    IS_USER_LOGGED_IN: "IS_USER_LOGGED_IN",
    LOGIN_USER: "LOGIN_USER",
    POPULATE_USER: "POPULATE_USER",
    POPULATE_USER_BART_STATIONS: "POPULATE_USER_BART_STATIONS"
};
