FROM tutum/nginx
RUN rm /etc/nginx/sites-enabled/default
ADD /docker/nginx/sites-enabled /etc/nginx/sites-enabled

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 80 443